include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Add additional rules here

    # --- Best Practices ---
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_single_quotes: true
    use_function_type_syntax_for_parameters: true





    # --- Readability ---
    avoid_multiple_declarations_per_line: true
    sort_constructors_first: true
    prefer_typing_uninitialized_variables: true

    # --- Error Handling ---
    avoid_catches_without_on_clauses: true
    avoid_void_async: true

    # --- Code Size Optimization ---
    avoid_redundant_argument_values: true
    prefer_if_elements_to_conditional_expressions: true
    avoid_renaming_method_parameters: true

    # --- Flutter Specific ---
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true

    # --- Effective Dart ---
    avoid_empty_else: true
    await_only_futures: true



analyzer:
  errors:
    avoid_print: error
    prefer_single_quotes: error


  exclude:
    - "**/*.g.dart"  # Ignore generated files
    - "**/*.freezed.dart"
    - "**/build/**"

